name: Bug report
description: Report a problem to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes:
      label: What happened?
      description: Please describe the bug and expected behavior.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      render: shell