name: Feature request
description: Suggest an idea or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: context
    attributes:
      label: Additional context