name: ci
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install biopython scikit-learn joblib pandas matplotlib pytest

      - name: Lint (non-blocking)
        continue-on-error: true
        run: |
          python -m pip install ruff black
          ruff check .
          black --check .

      - name: Run smoke tests
        run: |
          pytest -q